[package]
name = "wasm-mergers"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { version = "1.0.97" }
thiserror = { version = "2.0.12" }
walrus = { version = "0.23.3" }
derive_more = { version = "2", features = ["from", "into", "from_str"] }

[dev-dependencies]
wasmtime = { version = "31.0.0" }
wat = { version = "1.228.0" }
